
#################### default parameters ################################
logo = "images/logo.svg"
footer = "images/footer.svg"
logo_width = "250px"
# OpenGraph / Twitter Card metadata
description = "This is meta description"
author = "Themefisher"
image = "images/logo.svg" # this image will be used as fallback if a page has no image of its own
# contact form action
contact_form_action = "#" # contact form works with https://formspree.io
favicon = "images/favicon.png"
# Type of pages to be rendered with a blog view
blogCategoryType = "category"

# Preloader
[preloader]
enable = false
preloader = "" # use jpg, png, svg or gif format.

# Navigation buttons
[navigation_button]
enable = true
label = "Contact us"
link = "#contact"

# cookies
[cookies]
enable = false
expire_days = 2
content = "This site uses cookies. By continuing to use this website, you agree to their use."
button = "I Accept"

############################# social site ########################
[[social]]
title = "linkedin"
icon = "fab fa-linkedin" # themify icon : https://themify.me/themify-icons
link = "https://www.linkedin.com/company/rubber-duck-software-ro"
